### PR TITLE
Enabled pytorch build on PPC64LE

### PR DESCRIPTION
**Pull request by kamasubb**
Added support for PPC64LE build
Added fixes of known issues as patches

### CODE REVIEW

**Comment by jjhelmus** [comment]
@kamasubb can you provide some details on the environment in which this recipe can be built?  Our current PyTorch packages are built inside a Docker container as described in the [README](https://github.com/AnacondaRecipes/aggregate/blob/master/pytorch-feedstock/recipe/README) file.  Are you using something similar for the PPC64LE builds?

**Comment by kamasubb** [comment]
@jjhelmus I used the container image that was created for PPC64LE based on NVIDIA container image. This is similar to the one mentioned in the README. It has CUDA 9.1 and CUDNN 7. The image (kamasubb/conda-forge-linux-anvil-ppc64le) is available in docker hub.

**Comment by jjhelmus** [comment]
@kamasubb Can you provide a link to the Dockerfile used to create the image?

It looks like this recipe depend on the system providing the compiler toolchain and the CUDA libraries.  We use conda provides versions of both of these in our x86_64 PyTorch packages.  Can something similar be done here?

**Comment by kamasubb** [comment]
@jjhelmus Location of Dockerfile https://github.com/kamasubb/conda-forge-docker-image/blob/master/centos/7.5/DockerFile

**Comment by jjhelmus** [comment]
@kamasubb There seems to be a number of files which need to be in the working directory to build the Docker container you linked to.  The image we use for our builds can be found in the [conda-concourse-ci repository](https://github.com/conda/conda-concourse-ci/tree/master/docker/c3i-linux-ppc64le), can you build an image starting from that?  Checking that it can build from a clean clone without any external or local requirements would be most helpful.

Additionally, the CUDA libraries must be provided by a conda package at runtime.  Currently we only have `cudatoolkit` version 8.0 in our repository for the linux-ppc64le platform.  Can PyTorch use this version or is an update to this package needed?  We would also greatly prefer that the compiler for the build to be provided by conda.

**Comment by jjhelmus** [comment]
I was able to get PyTorch to build inside a CentOS 7 Docker container with CUDA 9.1 but the unit tests fail:

```
Running test_cuda ...
CUDA not available, skipping tests
...............s.......s..........................sss.......................s....s................ss............sss..................s....................................................ss.....ss.........F............................ss........s...............................ss....................s.....ss..ss
======================================================================
FAIL: test_qr (test_torch.TestTorch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/conda-bld/pytorch_1526665085183/test_tmp/test/common.py", line 66, in wrapper
    fn(*args, **kwargs)
  File "/opt/conda/conda-bld/pytorch_1526665085183/test_tmp/test/test_torch.py", line 3133, in test_qr
    self.assertEqual(a, a_qr, prec=1e-3)
  File "/opt/conda/conda-bld/pytorch_1526665085183/test_tmp/test/common.py", line 243, in assertEqual
    assertTensorsEqual(x, y)
  File "/opt/conda/conda-bld/pytorch_1526665085183/test_tmp/test/common.py", line 235, in assertTensorsEqual
    self.assertLessEqual(max_err, prec, message)
AssertionError: tensor(4.5535) not less than or equal to 0.001 : 

----------------------------------------------------------------------
```

**Comment by Karthikmvd** [comment]
The unit test failure is due to below pytorch issue:
https://github.com/pytorch/pytorch/issues/3716

**Comment by Karthikmvd** [comment]
@jjhelmus I am bulding a new image using conda-concourse-ci repository. Will let you know the out come as soon as possible.

**Comment by ipoddar-ibm** [comment]
@jjhelmus since the test failure seems to be a known issue, can you publish the package while we identify a resolution? 

Also can you point us to the recipe for cudatoolkit 8.0, NVidia has recently published toolkit version 9.2 which is needed for POWER9. We could provide a PR for the recipe and the new version of the toolkit. thanks

**Review by varlackc — COMMENTED** [review]
This PR has been open for a few years at this point, maybe we should close it at this point.

**Comment by ryanskeith** [comment]
Closing as we build pytorch from a submodule.

**Pull request closed without merging**
