### PR TITLE
CMAKE_PREFIX_PATH for clang and vs

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
cc @ocefpaf, this should fix the openssl issue we had automatically.

**Comment by isuruf** [comment]
Thanks @msarahan

**Comment by ocefpaf** [comment]
> cc @ocefpaf, this should fix the openssl issue we had on windows automatically.

Awesome! Thanks @isuruf for the PR and @msarahan for the merge.

Mike, please ping us when the new packages are available. (I'm assuming there is no automatic build after the merge, right?)

**Comment by msarahan** [comment]
it'll be a little later today.

**Pull request merged**
