### PR TITLE
10-group migrations

### PR DESCRIPTION
**Pull request by ryanskeith**
Migrating feedstocks in the 10-group from being root to having their own feedstocks.

Diffs were done using diff -rq aggregate/<feedstock> migration/<feedstock> on every feedstock.  Here where each of the results:

gevent-websocket-feedstock:
   No differences found.

gfortran-feedstock:
   No differences found.

git-cola-feedstock:
   No differences found.

gptfdisk-feedstock:
   No differences found.

grako-feedstock:
   No differences found.

### CODE REVIEW

**Review by varlackc — APPROVED** [review]
LGTM

**Review by boldorider4 — COMMENTED** [review]
I don't fully understand this PR.

Here I see feedstocks that were added to aggregate as simples directories and files and not as submodules and are now being removed. From what I understand these should become submodules.

I think for this migration to be fully represented in the PR the following should be done:

- create repos in AnacondaRecipes for each of those feedstock (I checked a few of those and they still don't exist)
- open a PR where:
  - feedstock files get deleted from aggregate (i.e. the content of this PR)
  - .gitmodule gets updated with submodule information of each feedstock (e.g. below)
> [submodule "gevent-websocket-feedstock"]
>         url = ../gevent-websocket-feedstock.git
>         path = gevent-websocket-feedstock
>         branch = main

At this point it makes sense for us to review that those feedstocks that have been migrated did not change.

**Comment by boldorider4** [comment]
OK, I reviewed the script you posted on slack.
I suppose it looks good. The only part that confuses me still is that I see this line:

> !git submodule add -b main https://github.com/AnacondaRecipes/{dirname}

So this means that the repo for the migrated feedstock should already exist. And it should also be added to the .gitmodule file and the change should be visible since you do:

> !gh pr create --title "{pr_title}" --body "{pr_body}" 

So I'm still confused as to why the PR only shows removed files.

**Comment by ryanskeith** [comment]
@boldorider4 You are correct. Looking at my logs it seems there were consecutive git errors on migrations 7 - 11. I will need to fix them.  I checked and all feedstocks were successfully created.  I will not merge these 5 migrations.  All 35 of these migrations were auto generated as there were a lot.  I wanted to do them in small enough chunks that it would be obvious if errors occurred.

**Comment by ryanskeith** [comment]
@boldorider4 which repositories did you not find?

**Review by boldorider4 — APPROVED** [review]
@ryanskeith I do find the repos in AnacondaRecipes now. Not sure why I wasn't finding them earlier.
Thanks for updating .gitmodule!
LGTM now.

**Pull request merged**
