### PR TITLE
ENH enable -ffast-math

### PR DESCRIPTION
**Pull request by beckermr**
@isuruf @mingwandroid @msarahan

I went ahead and made a PR to fix this since some of the conda-forge rebuilds are failing due to this missing file. IDK if this is the right spot, but it seems like it.

### CODE REVIEW

**Comment by beckermr** [comment]
Any updates on this @nehaljwani @csoja?

**Comment by msarahan** [comment]
I'm not sure we can actually do this.  Yes, there's a large speedup here, but the numerical risk is way too high to be a default setting for everything.  More info about exactly what this flag does is at https://stackoverflow.com/a/22135559/1170370

**Comment by msarahan** [comment]
Oh, sorry.  I misunderstood this PR.  -ffast-math is not our default, and this doesn't change it.  This PR is fine.  Please also bump the build number.  To be clear, this is only applying to gfortran on osx.  Is that the intent?

**Comment by beckermr** [comment]
I’m not saying we use it by default. I am asking y’all to package the file for people who want to use the flag at their own risk. Are you suggesting even giving people the ability is too much?

**Comment by beckermr** [comment]
Ahhh great! I’ll bump the build number.

**Comment by beckermr** [comment]
OK @msarahan  @nehaljwani @csoja, I have bumped the build number. 

I did intend to apply this fix only to osx. As far as I can tell, the linux packages have the proper fast-math files. IDK about windows which is always complicated.

**Comment by mingwandroid** [comment]
Thanks!

**Pull request merged**
