### PR TITLE
Fix version of clang, clangxx required by clang_osx-64

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by jakirkham** [comment]
@mingwandroid, what are your thoughts on this?

**Comment by jjhelmus** [comment]
Packages with these changes are now available in `pkgs/main`.  

Sorry for the delay in merging this @isuruf.

**Comment by isuruf** [comment]
Thanks.

**Comment by isuruf** [comment]
@jjhelmus, how do you feel about bumping the version to 8.0.0 ? conda-forge has all the components except for this activation package.

**Comment by jjhelmus** [comment]
> how do you feel about bumping the version to 8.0.0 ?

We (Anaconda) are in favor of updating to the latest clang but it will take some time for us to check compatibility and roll it out.

**Comment by isuruf** [comment]
Okay, I'll go with https://github.com/conda-forge/staged-recipes/pull/9072 then. We'll still use 4.0.1 as the compiler in conda-forge, but it's nice to have an up-to-date compiler for newer packages.

**Comment by mingwandroid** [comment]
@isuruf, how's thinngs looking for clang-8 on macOS now? Have you built clang-8 with clang-4.0.1 for example then verified that things built with clang-4.0.1 work when running against the language runtime libs from clang-8?

I'm pretty sure you will have done, but figured I'd ask to be sure!

**Comment by isuruf** [comment]
> how's thinngs looking for clang-8 on macOS now? Have you built clang-8 with clang-4.0.1 for example

Yes.

> then verified that things built with clang-4.0.1 work when running against the language runtime libs from clang-8?

We at conda-forge use `libcxx-8.0.0` by default, but compile with `clang-4.0.1`

**Comment by isuruf** [comment]
We also have `clang-8.0.0` for linux that will use the gcc sysroot when `export CONDA_BUILD_SYSROOT=$PREFIX/$HOST/sysroot` is given. (I'm going to add that to the activation script when `CONDA_BUILD=1` is set.)
`clang-8.0.0` for windows works fine too when the VS environment is activated.

**Comment by isuruf** [comment]
We do check a couple of projects when releasing a new `libcxx` version. https://github.com/conda-forge/libcxx-feedstock/blob/master/recipe/meta.yaml#L51-L55

**Comment by mingwandroid** [comment]
Great stuff, many thanks @isuruf! So to be clear (and probably annoying) a Qt 5.12 built with 4.0.1 is known to work with libc++ from 8?

.. BTW 8.0.1 is out now I think.

**Comment by mingwandroid** [comment]
> We also have clang-8.0.0 for linux that will use the gcc sysroot when export CONDA_BUILD_SYSROOT=$PREFIX/$HOST/sysroot is given. (I'm going to add that to the activation script when CONDA_BUILD=1 is set.)
clang-8.0.0 for windows works fine too when the VS environment is activated.

Also very cool. I want this!

What are your thoughts on libc++ for Linux and llvm-openmp instead of libgomp?

**Comment by isuruf** [comment]
I don't know about Qt 5.12, but Qt 5.9.7 built with 4.0.1 works just fine with libcxx 8.0.0

**Comment by isuruf** [comment]
My thoughts on openmp are at https://github.com/conda-forge/conda-forge.github.io/issues/831

**Pull request merged**
