### PR TITLE
pytorch: lazy symbol binding for cpu support

### PR DESCRIPTION
**Pull request by jjhelmus**
Enable lazy symbol binding for CPU support

### CODE REVIEW

**Comment by jjhelmus** [comment]
@mingwandroid Can you have a look at this.  Changing the link argument to  lazy binding solves the issue with the package not importing on system with a GPU.

**Comment by jjhelmus** [comment]
FYI, sample package are available in my channel, `jjhelmus`

**Comment by mingwandroid** [comment]
Can we set this only for the exact DSO that needs it? And can we also report it upstream as a security concern to upstream?

**Comment by jjhelmus** [comment]
> Can we set this only for the exact DSO that needs it?

I believe there are multiple DSOs that need to be linked in this manner.  I can try to identify all of them.  What is the mechanism for specifying to the linker specific DSO to bind lazily?


> And can we also report it as a security concern to upstream?

I can raise this concern upstream but I believe this was an intentional choice by the project.

**Comment by mingwandroid** [comment]
I doubt they intend to make all of their DSOs less secure due to a single instance of the need to do weak binding to be honest, rather, it will probably be just be that they have not thought about this security matter at all (in general, until `bind now` is enabled by default across all linux distros this will continue to be the case).

I don't know the `pytorch` build system, but you need to modify the `LDFLAGS` for the single DSO that had the problem.

**Pull request merged**
