### PR TITLE
Add mkl repack

### PR DESCRIPTION
**Pull request by msarahan**
CC @tomashek

### CODE REVIEW

**Comment by tomashek** [comment]
The license files look like older versions. Did you get them from the packages on the intel/label/test channel?

**Comment by msarahan** [comment]
The license files are obtained directly from the packages that are being repacked: https://github.com/AnacondaRecipes/aggregate/pull/3/files#diff-a959083f53cca8390cdce0b8b051ed80R2

The license files in this PR actually should be removed.  Thanks.

**Comment by tomashek** [comment]
Good, thanks

**Comment by tomashek** [comment]
I'm not certain about adding the compiler runtimes as a dependency. MKL does not depend on them. Do you know that they are needed by users? Or are you just preserving them "just in case"?

**Comment by msarahan** [comment]
Just in case. Since our existing mkl packages include them, we need to
maintain that behavior, at least until we can prove that no one depends on
them being there.

**Comment by tomashek** [comment]
I understand the hesitancy to change, but I hate promulgating a legacy dependency for no reason. The "proving it is not needed" ends up never happening and the status quo lives on in perpetuity.

Removing them is likely the only way you will ever know if anyone is unwittingly depending on them.

If a user environment needs the compiler runtimes, then they can add the package as they need to.

**Comment by tomashek** [comment]
I am double and triple checking with the MKL team on the dependency. We can talk this afternoon more if needed.

**Comment by msarahan** [comment]
I certainly understand your point of view, but I'm hesitant to do anything that increases the risk for the Anaconda 5.0 release.  There is already a daunting number of changes with the potential to break things.  Let's talk about this at our meeting in a bit.

**Comment by tomashek** [comment]
The only MKL runtime requirement is openmp. We list openmp as a dependency of both icc_rt and MKL, but it looks like you removed it from both. That should be included, and the openmp package added to this set of aggregates.

**Pull request merged**
