### PR TITLE
Add weasel-feedstock

### PR DESCRIPTION
**Pull request by skupr-anaconda**
### Explanation of changes:

- The weasel-feedstock got this error for Python 3.12, see https://github.com/AnacondaRecipes/weasel-feedstock/pull/1#issuecomment-1870468061:
` INFO   Running command: git clone -b 3.12 --depth 1 git@github.com:AnacondaRecipes/aggregate.git "/tmp/abs_15739res_j/clone/.abs"
`

We missing it in `.gitmodules` in the `3.12` branch not in `master`

### CODE REVIEW

**Comment by rafaelmartins** [comment]
probably the best way to fix this is to rebase branch `3.12` against `master`. this new commit may generate a merge conflict later. alternatively, just add `aggregate_check: false` to your `abs.yaml`, as it is already in master and this branch will be merged soon or later.

**Comment by skupr-anaconda** [comment]
> probably the best way to fix this is to rebase branch `3.12` against `master`. this new commit may generate a merge conflict later. alternatively, just add `aggregate_check: false` to your `abs.yaml`, as it is already in master and this branch will be merged soon or later.

Adding `aggregate_check: false` doesn't work
https://github.com/AnacondaRecipes/weasel-feedstock/pull/1/commits/d289821c4182ca7756be8e5fdaa1a7d878c45e84

@JeanChristopheMorinPerso How should we rebase branch `3.12` against `master` correctly as not all new feedstocks haven't been built against python 3.12 yet?

**Comment by rafaelmartins** [comment]
this branch only applies cbc.yaml changes. which packages were built with 3.12 already or not is probably irrelevant. I see that people are usually merging master to 3.12, you can probably just do the same. I mentioned rebase because that's what I'd do instead of merging master back and messing with history in a temp branch, but merging should be fine.

**Comment by cbouss** [comment]
The 3.12 branch is meant as a temporary branch to not force everyone to build for 3.12. 
It has so far been kept up-to-date by merging master back to it.

**Comment by rafaelmartins** [comment]
yeah, that's what I meant, merge back to 3.12, not the opposite :)

**Comment by skupr-anaconda** [comment]
@rafaelmartins @cbouss I hope that I rebased `master` to `3.12` correctly

**Comment by lorepirri** [comment]
@skupr-anaconda then this one PR can be closed right?

**Comment by cbouss** [comment]
I udpated the 3.12 branch outside of the PR.

**Pull request closed without merging**
