### PR TITLE
Final submodule standardization of aggregate

### PR DESCRIPTION
**Pull request by ryanskeith**
Removed the following as root level feedstocks in aggregate:
  - The underscore group
    \_ipyw_jlab_nb_ext_conf-feedstock
    \_low_priority-feedstock
    \_pytorch_select
  - The build and most likely very normal group
      cdt_cos6_i686
      cdt_cos6_x86_64
      cdt_cos7_ppc64le
      cdt_cos7_s390x
      clang
      clang-dbg
      intel-fortran
      m2w64-libxml2
      vs2008
      vs2010
      vs2015
      vs2017
      vs2019

These were copied to [aggregate-deprecated](https://github.com/AnacondaRecipes/aggregate-deprecated/tree/main/old_root_feedstocks):
- cdt_cos6_i686
- clang
- clang-dbg
- m2w64-libxml2
- vs2008
- vs2010

These were made into feedstocks and added back into aggregate as submodules:
- _ipyw_jlab_nb_ext_conf-feedstock
 - _pytorch_select  -> _pytorch_select-feedstock
 - _low_priority-feedstock
 - cdt_cos6_x86_64 -> cdt_cos6_x86_64-feedstock 
 - cdt_cos7_ppc64le -> cdt_cos7_ppc64le-feedstock
 - cdt_cos7_s390x -> cdt_cos7_s390x-feedstock
 - intel-fortran -> intel-fortran-feedstock
 - vs2015 -> vs2015-feedstock
 - vs2017  -> vs2017-feedstock
 - vs2019  -> vs2019-feedstock

### CODE REVIEW

**Comment by JeanChristopheMorinPerso** [comment]
I feel like `cdt_cos6_x86_64-feedstock`, `cdt_cos7_ppc64le-feedstock` and `cdt_cos7_s390x-feedstock` woucl almost named "feedstock**s**".

**Review by cbouss — APPROVED** [review]
LGTM

**Comment by ryanskeith** [comment]
@JeanChristopheMorinPerso We could make that change.  Though I would rather do it in a later PR with all the other groups like this.

**Review by markan — APPROVED** [review]
LGTM

**Pull request merged**
