### PR TITLE
Add -rpath-link for gcc compiler activation

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
ping

**Comment by jjhelmus** [comment]
This seems reasonable to me, @msarahan @mingwandroid do you have thoughts?

**Comment by mingwandroid** [comment]
Fine by me too.

**Comment by jakirkham** [comment]
Do you know when the Linux toolchain might next be rebuilt? Would be great to have this change in production :)

**Comment by isuruf** [comment]
Ping.

**Comment by msarahan** [comment]
@jjhelmus, since you merged this pr, please build this package.

**Comment by isuruf** [comment]
If you are using latest conda-build, use https://github.com/conda/conda-build/pull/3343. Otherwise tests will not be run

**Comment by jjhelmus** [comment]
Packages with this change are now available in `pkgs/main` as {gcc/gxx/gfortran}-linux-{64/ppc64le} version 7.3.0 build 3 and 8.2.0 build 6.

**Comment by msarahan** [comment]
Thanks @jjhelmus

**Pull request merged**
